[params]

[operators]
node = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route = [
    "RelocateStar",
    "SwapStar",
]

crossover = [
    "broken_pairs_exchange",
    "selective_route_exchange"
]
