[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]

strategy = "rollout"

[dynamic.solver_params]
nbIter = 250

[dynamic.strategy_params]
rollout_tlim_factor = 0.50
n_simulations = 40
n_lookahead = 1
n_requests = 100
dispatch_threshold = 0.35

node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic.strategy_params.sim_config]
seed = 1
collectStatistics = true
generationSize = 10
minPopSize = 3
nbElite = 2
nbGranular = 40
nbPenaltyManagement = 1
