[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]

[static.params]
minPopSize = 92
generationSize = 36
nbElite = 23
lbDiversity = 0.11742424242424243
ubDiversity = 0.5795454545454546
nbClose = 10
nbIter = 5318
