[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]
