[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]

strategy = "rollout"

[dynamic.strategy_params]
n_lookahead = 3
n_requests = 100
sim_tlim_factor = 0.6
sim_solve_iters = 40
dispatch_threshold = 0.15
n_sim_cycles = 3
sim_cycle_length = 50

node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic.strategy_params.sim_config]
seed = 1
generationSize = 2
minPopSize = 1
nbGranular = 70
initialTimeWarpPenalty = 25
penaltyDecrease = 0.25
nbPenaltyManagement = 1
repairProbability = 0
