[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]

strategy = "rollout"

[dynamic.strategy_params]
rollout_tlim_factor = 0.7
n_cycles = 1
n_simulations = 50
n_lookahead = 1
n_requests = 100
dispatch_threshold = 0.35

node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic.strategy_params.sim_config]
seed = 1
seed = 1
initialTimeWarpPenalty = 14
nbPenaltyManagement = 1
feasBooster = 9.045454545454545
penaltyIncrease = 2.0303030303030303
penaltyDecrease = 0.33712121212121215
targetFeasible = 0.18686868686868688
repairProbability = 53
repairBooster = 10
minPopSize = 3
generationSize = 8
shouldIntensify = 0
nbGranular = 16
weightWaitTime = 5
weightTimeWarp = 18
