[static]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic]
node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]

strategy = "simulate"


[dynamic.params]
nbGranular = 30
weightWaitTime = 2
weightTimeWarp = 5
postProcessPathLength = 1
initialTimeWarpPenalty = 1
nbPenaltyManagement = 100
feasBooster = 2.0
penaltyIncrease = 1.2
penaltyDecrease = 0.85
targetFeasible = 0.4
repairProbability = 50
repairBooster = 10
minPopSize = 38
generationSize = 32
nbElite = 10
lbDiversity = 0.14015151515151514
ubDiversity = 0.36742424242424243
nbClose = 17
nbIter = 6318


[dynamic.strategy_params]
simulate_tlim_factor = 0.7703517587939699
n_cycles = 3
n_simulations = 40
n_lookahead = 5
n_requests = 69
postpone_thresholds = [
    0.6289158289264459,
    0.8485448714466843,
    0.7330547338912516,
    0.8039337145760462,
]

node_ops = [
    "Exchange10",
    "Exchange11",
    "Exchange20",
    "MoveTwoClientsReversed",
    "Exchange21",
    "Exchange22",
    "TwoOpt",
]

route_ops = [
    "RelocateStar",
    "SwapStar",
]

crossover_ops = [
    "selective_route_exchange",
]


[dynamic.strategy_params.sim_config]
seed = 1
initialTimeWarpPenalty = 14
nbPenaltyManagement = 1
feasBooster = 9.045454545454545
penaltyIncrease = 2.0303030303030303
penaltyDecrease = 0.33712121212121215
targetFeasible = 0.18686868686868688
repairProbability = 53
repairBooster = 10
minPopSize = 3
generationSize = 8
shouldIntensify = 0
nbGranular = 16
weightWaitTime = 5
weightTimeWarp = 18
