name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ "ubuntu-latest"]
        python-version: [ '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Make all
        run: |
          cmake -Brelease -Shgs_vrptw && cd release && make
      - name: Test controller
        run: |
          poetry run python controller.py --instance instances/ORTEC-VRPTW-ASYM-0bdff870-d1-n458-k35.txt --epoch_tlim 5 -- python solver.py
          poetry run python controller.py --instance instances/ORTEC-VRPTW-ASYM-0bdff870-d1-n458-k35.txt --epoch_tlim 30 --static -- python solver.py
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'hgs_vrptw'
          extensions: 'h,cpp'
          clangFormatVersion: 10
          exclude: 'hgs_vrpt/extern/*'
