name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest"]
        python-version: [ '3.9', '3.10' ]
        compiler: [ 'gcc', 'clang' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: matrix.compiler == 'clang'
        name: Set up clang
        uses: egor-tensin/setup-clang@v1
      - if: matrix.compiler == 'gcc'
        name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Make all
        run: |
          cmake -Brelease -Shgs_vrptw && cd release && make
      - name: Test controller
        run: |
          poetry run python controller.py --instance instances/ORTEC-VRPTW-ASYM-0bdff870-d1-n458-k35.txt --epoch_tlim 30 --static -- python solver.py
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'hgs_vrptw/src hgs_vrptw/include hgs_vrptw/test'
          extensions: 'h,cpp'
          clangFormatVersion: 10
